drop table if exists users;
create table users (
user_id integer primary key autoincrement,
login         varchar(25) not null,
password_hash varchar(25) not null
);

drop table if exists authors;
create table authors (
author_id integer primary key autoincrement,
name         varchar(25) not null
);


drop table if exists books;
create table books (
book_id integer primary key autoincrement,
name         varchar(25) not null
);


drop table if exists relation;
create table relation (
book_id integer not null,
author_id integer not null,
primary key (book_id, author_id)
);

insert into users(login, password_hash) values('Admin', 'Admin');

drop table if exists tmp_authors_books;
create table tmp_authors_books(
		book   varchar(70),
		author varchar(70)
		);

insert into tmp_authors_books(book, author)
values('The Lord of the Rings', 'J. R. R. Tolkien')
,('Pride and Prejudice', 'Jane Austen')
,('His Dark Materials', 'Philip Pullman')
,('The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams')
,('Harry Potter and the Goblet of Fire', 'J. K. Rowling')
,('To Kill a Mockingbird', 'Harper Lee')
,('Winnie-the-Pooh', 'A. A. Milne')
,('Nineteen Eighty-Four', 'George Orwell')
,('The Lion, the Witch and the Wardrobe', 'C. S. Lewis')
,('Jane Eyre', 'Charlotte Brontë')
,('Catch-22', 'Joseph Heller')
,('Wuthering Heights', 'Emily Brontë')
,('Birdsong', 'Sebastian Faulks')
,('Rebecca', 'Daphne du Maurier')
,('The Catcher in the Rye', 'J. D. Salinger')
,('The Wind in the Willows', 'Kenneth Grahame')
,('Great Expectations', 'Charles Dickens')
,('Little Women', 'Louisa May Alcott')
,('Captain Corelli''s Mandolin', 'Louis de Bernières')
,('War and Peace', 'Leo Tolstoy')
,('Gone with the Wind', 'Margaret Mitchell')
,('Harry Potter and the Philosopher''s Stone', 'J. K. Rowling')
,('Harry Potter and the Chamber of Secrets', 'J. K. Rowling')
,('Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling')
,('The Hobbit', 'J. R. R. Tolkien')
,('Tess of the d''Urbervilles', 'Thomas Hardy')
,('Middlemarch', 'George Eliot')
,('A Prayer for Owen Meany', 'John Irving')
,('The Grapes of Wrath', 'John Steinbeck')
,('Alice''s Adventures in Wonderland', 'Lewis Carroll')
,('The Story of Tracy Beaker', 'Jacqueline Wilson')
,('One Hundred Years of Solitude', 'Gabriel García Márquez')
,('The Pillars of the Earth', 'Ken Follett')
,('David Copperfield', 'Charles Dickens')
,('Charlie and the Chocolate Factory', 'Roald Dahl')
,('Treasure Island', 'Robert Louis Stevenson')
,('A Town Like Alice', 'Nevil Shute')
,('Persuasion', 'Jane Austen')
,('Dune', 'Frank Herbert')
,('Emma', 'Jane Austen')
,('Anne of Green Gables', 'Lucy Maud Montgomery')
,('Watership Down', 'Richard Adams')
,('The Great Gatsby', 'F. Scott Fitzgerald')
,('The Count of Monte Cristo', 'Alexandre Dumas')
,('Brideshead Revisited', 'Evelyn Waugh')
,('Animal Farm', 'George Orwell')
,('A Christmas Carol', 'Charles Dickens')
,('Far from the Madding Crowd', 'Thomas Hardy')
,('Goodnight Mister Tom', 'Michelle Magorian')
,('The Shell Seekers', 'Rosamunde Pilcher')
,('The Secret Garden', 'Frances Hodgson Burnett')
,('Of Mice and Men', 'John Steinbeck')
,('The Stand', 'Stephen King')
,('Anna Karenina', 'Leo Tolstoy')
,('A Suitable Boy', 'Vikram Seth')
,('The BFG', 'Roald Dahl')
,('Swallows and Amazons', 'Arthur Ransome')
,('Black Beauty', 'Anna Sewell')
,('Artemis Fowl', 'Eoin Colfer')
,('Crime and Punishment', 'Fyodor Dostoevsky')
,('Noughts & Crosses', 'Malorie Blackman')
,('Memoirs of a Geisha', 'Arthur Golden')
,('A Tale of Two Cities', 'Charles Dickens')
,('The Thorn Birds', 'Colleen McCullough')
,('Mort', 'Terry Pratchett')
,('The Magic Faraway Tree', 'Enid Blyton')
,('The Magus', 'John Fowles')
,('Good Omens', 'Neil Gaiman and Terry Pratchett')
,('Guards! Guards!', 'Terry Pratchett')
,('Lord of the Flies', 'William Golding')
,('Perfume', 'Patrick Süskind')
,('The Ragged-Trousered Philanthropists', 'Robert Tressell')
,('Night Watch', 'Terry Pratchett')
,('Matilda', 'Roald Dahl')
,('Bridget Jones''s Diary', 'Helen Fielding')
,('The Secret History', 'Donna Tartt')
,('The Woman in White', 'Wilkie Collins')
,('Ulysses', 'James Joyce')
,('Bleak House', 'Charles Dickens')
,('Double Act', 'Jacqueline Wilson')
,('The Twits', 'Roald Dahl')
,('I Capture the Castle', 'Dodie Smith')
,('Holes', 'Louis Sachar')
,('Gormenghast', 'Mervyn Peake')
,('The God of Small Things', 'Arundhati Roy')
,('Vicky Angel', 'Jacqueline Wilson')
,('Brave New World', 'Aldous Huxley')
,('Cold Comfort Farm', 'Stella Gibbons')
,('Magician', 'Raymond E. Feist')
,('On the Road', 'Jack Kerouac')
,('The Godfather', 'Mario Puzo')
,('The Clan of the Cave Bear', 'Jean M. Auel')
,('The Colour of Magic', 'Terry Pratchett')
,('The Alchemist', 'Paulo Coelho')
,('Katherine', 'Anya Seton')
,('Kane and Abel', 'Jeffrey Archer')
,('Love in the Time of Cholera', 'Gabriel García Márquez')
,('Girls in Love', 'Jacqueline Wilson')
,('The Princess Diaries', 'Meg Cabot')
,('Midnight''s Children', 'Salman Rushdie')
,('Three Men in a Boat', 'Jerome K. Jerome')
,('Small Gods', 'Terry Pratchett')
,('The Beach', 'Alex Garland')
,('Dracula', 'Bram Stoker')
,('Point Blanc', 'Anthony Horowitz')
,('The Pickwick Papers', 'Charles Dickens')
,('Stormbreaker', 'Anthony Horowitz')
,('The Wasp Factory', 'Iain Banks')
,('The Day of the Jackal', 'Frederick Forsyth')
,('The Illustrated Mum', 'Jacqueline Wilson')
,('Jude the Obscure', 'Thomas Hardy')
,('The Secret Diary of Adrian Mole, Aged 13¾', 'Sue Townsend')
,('The Cruel Sea', 'Nicholas Monsarrat')
,('Les Misérables', 'Victor Hugo')
,('The Mayor of Casterbridge', 'Thomas Hardy')
,('The Dare Game', 'Jacqueline Wilson')
,('Bad Girls', 'Jacqueline Wilson')
,('The Picture of Dorian Gray', 'Oscar Wilde')
,('Shōgun', 'James Clavell')
,('The Day of the Triffids', 'John Wyndham')
,('Lola Rose', 'Jacqueline Wilson')
,('Vanity Fair', 'William Makepeace Thackeray')
,('The Forsyte Saga', 'John Galsworthy')
,('House of Leaves', 'Mark Z. Danielewski')
,('The Poisonwood Bible', 'Barbara Kingsolver')
,('Reaper Man', 'Terry Pratchett')
,('Angus, Thongs and Full-Frontal Snogging', 'Louise Rennison')
,('The Hound of the Baskervilles', 'Arthur Conan Doyle')
,('Possession: A Romance', 'A. S. Byatt')
,('The Master and Margarita', 'Mikhail Bulgakov')
,('The Handmaid''s Tale', 'Margaret Atwood')
,('Danny, the Champion of the World', 'Roald Dahl')
,('East of Eden', 'John Steinbeck')
,('George''s Marvellous Medicine', 'Roald Dahl')
,('Wyrd Sisters', 'Terry Pratchett')
,('The Color Purple', 'Alice Walker')
,('Hogfather', 'Terry Pratchett')
,('The Thirty-nine Steps', 'John Buchan')
,('Girls in Tears', 'Jacqueline Wilson')
,('Sleepovers', 'Jacqueline Wilson')
,('All Quiet on the Western Front', 'Erich Maria Remarque')
,('Behind the Scenes at the Museum', 'Kate Atkinson')
,('High Fidelity', 'Nick Hornby')
,('It', 'Stephen King')
,('James and the Giant Peach', 'Roald Dahl')
,('The Green Mile', 'Stephen King')
,('Papillon', 'Henri Charrière')
,('Men at Arms', 'Terry Pratchett')
,('Master and Commander', 'Patrick O''Brian')
,('Skeleton Key', 'Anthony Horowitz')
,('Soul Music', 'Terry Pratchett')
,('Thief of Time', 'Terry Pratchett')
,('The Fifth Elephant', 'Terry Pratchett')
,('Atonement', 'Ian McEwan')
,('Secrets', 'Jacqueline Wilson')
,('The Silver Sword', 'Ian Serraillier')
,('One Flew Over the Cuckoo''s Nest', 'Ken Kesey')
,('Heart of Darkness', 'Joseph Conrad')
,('Kim', 'Rudyard Kipling')
,('Cross Stitch', 'Diana Gabaldon')
,('Moby-Dick', 'Herman Melville')
,('River God', 'Wilbur Smith')
,('Sunset Song', 'Lewis Grassic Gibbon')
,('The Shipping News', 'E. Annie Proulx')
,('The World According to Garp', 'John Irving')
,('Lorna Doone', 'R. D. Blackmore')
,('Girls Out Late', 'Jacqueline Wilson')
,('The Far Pavilions', 'M. M. Kaye')
,('The Witches', 'Roald Dahl')
,('Charlotte''s Web', 'E. B. White')
,('Frankenstein', 'Mary Shelley')
,('They Used to Play on Grass', 'Terry Venables and Gordon Williams')
,('The Old Man and the Sea', 'Ernest Hemingway')
,('The Name of the Rose', 'Umberto Eco')
,('Sophie''s World', 'Jostein Gaarder')
,('Dustbin Baby', 'Jacqueline Wilson')
,('Fantastic Mr. Fox', 'Roald Dahl')
,('Lolita', 'Vladimir Nabokov')
,('Jonathan Livingston Seagull', 'Richard Bach')
,('The Little Prince', 'Antoine de Saint-Exupéry')
,('The Suitcase Kid', 'Jacqueline Wilson')
,('Oliver Twist', 'Charles Dickens')
,('The Power of One', 'Bryce Courtenay')
,('Silas Marner', 'George Eliot')
,('American Psycho', 'Bret Easton Ellis')
,('Diary of a Nobody', 'George and Weedon Grossmith')
,('Trainspotting', 'Irvine Welsh')
,('Goosebumps', 'R. L. Stine')
,('Heidi', 'Johanna Spyri')
,('Sons and Lovers', 'D. H. Lawrence')
,('The Unbearable Lightness of Being', 'Milan Kundera')
,('Man and Boy', 'Tony Parsons')
,('The Truth', 'Terry Pratchett')
,('The War of the Worlds', 'H. G. Wells')
,('The Horse Whisperer', 'Nicholas Evans')
,('A Fine Balance', 'Rohinton Mistry')
,('Witches Abroad', 'Terry Pratchett')
,('The Once and Future King', 'T. H. White')
,('The Very Hungry Caterpillar', 'Eric Carle')
,('Flowers in the Attic', 'V. C. Andrews');

insert into authors(name) select distinct author from tmp_authors_books;

insert into books(name) select distinct book from tmp_authors_books;

insert into relation select a.author_id, b.book_id from tmp_authors_books tmp join authors a on tmp.author = a.name join books b on tmp.book = b.name;

drop table tmp_authors_books;
